name: pub_cache_cleaner
author: Andrew Mezoni <andrew.mezoni@gmail.com>
version: 0.0.4
homepage: https://github.com/mezoni/pub_cache_cleaner
description: Utility to clean the pub cache from obsolete packages
dependencies:
  args: any
  path: any
